/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    FooterNavbar: typeof import('./src/components/FooterNavbar.vue')['default']
    HeaderNavbar: typeof import('./src/components/HeaderNavbar.vue')['default']
    LatexRenderer: typeof import('./src/components/LatexRenderer.vue')['default']
    LoadingAnimation: typeof import('./src/components/LoadingAnimation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextContent: typeof import('./src/components/TextContent.vue')['default']
    TitleBox: typeof import('./src/components/TitleBox.vue')['default']
  }
}
