/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AttributionsPage': RouteRecordInfo<'/AttributionsPage', '/AttributionsPage', Record<never, never>, Record<never, never>>,
    '/ContributionPage': RouteRecordInfo<'/ContributionPage', '/ContributionPage', Record<never, never>, Record<never, never>>,
    '/DescriptionPage': RouteRecordInfo<'/DescriptionPage', '/DescriptionPage', Record<never, never>, Record<never, never>>,
    '/DesignPage': RouteRecordInfo<'/DesignPage', '/DesignPage', Record<never, never>, Record<never, never>>,
    '/EducationPage': RouteRecordInfo<'/EducationPage', '/EducationPage', Record<never, never>, Record<never, never>>,
    '/EngineeringPage': RouteRecordInfo<'/EngineeringPage', '/EngineeringPage', Record<never, never>, Record<never, never>>,
    '/EntrepreneurshipPage': RouteRecordInfo<'/EntrepreneurshipPage', '/EntrepreneurshipPage', Record<never, never>, Record<never, never>>,
    '/HomePage': RouteRecordInfo<'/HomePage', '/HomePage', Record<never, never>, Record<never, never>>,
    '/ImplementationPage': RouteRecordInfo<'/ImplementationPage', '/ImplementationPage', Record<never, never>, Record<never, never>>,
    '/IntegratedHumanPracticesPage': RouteRecordInfo<'/IntegratedHumanPracticesPage', '/IntegratedHumanPracticesPage', Record<never, never>, Record<never, never>>,
    '/ModelPage': RouteRecordInfo<'/ModelPage', '/ModelPage', Record<never, never>, Record<never, never>>,
    '/NotebookPage': RouteRecordInfo<'/NotebookPage', '/NotebookPage', Record<never, never>, Record<never, never>>,
    '/NotFoundPage': RouteRecordInfo<'/NotFoundPage', '/NotFoundPage', Record<never, never>, Record<never, never>>,
    '/PromotionVideoPage': RouteRecordInfo<'/PromotionVideoPage', '/PromotionVideoPage', Record<never, never>, Record<never, never>>,
    '/ProofOfConceptPage': RouteRecordInfo<'/ProofOfConceptPage', '/ProofOfConceptPage', Record<never, never>, Record<never, never>>,
    '/RosterPage': RouteRecordInfo<'/RosterPage', '/RosterPage', Record<never, never>, Record<never, never>>,
    '/SafetyPage': RouteRecordInfo<'/SafetyPage', '/SafetyPage', Record<never, never>, Record<never, never>>,
    '/WebApplicationPage': RouteRecordInfo<'/WebApplicationPage', '/WebApplicationPage', Record<never, never>, Record<never, never>>,
  }
}
